import { TemplateItem, ShowcasePageData } from './types';

// ── Page Configs ──
export const SHOWCASE_PAGES: Record<string, ShowcasePageData> = {
    linknabio: {
        id: 'linknabio',
        title: 'Link na Bio',
        subtitle: 'Personalizado',
        description: 'Transforme seu perfil em uma vitrine profissional. Seu público vai clicar.',
        accentColor: '#a855f7',
        gradient: 'linear-gradient(135deg, #1a002e 0%, #3d0068 50%, #7b00cc 100%)',
    },
    ecommerce: {
        id: 'ecommerce',
        title: 'E-commerce',
        subtitle: 'Lojas que Vendem',
        description: 'Lojas online que convertem visitantes em compradores. Design que vende.',
        accentColor: '#f59e0b',
        gradient: 'linear-gradient(135deg, #1a0e00 0%, #3d2800 50%, #7a5000 100%)',
    },
    sites: {
        id: 'sites',
        title: 'Sites',
        subtitle: 'Impactantes',
        description: 'Sites que impressionam na primeira visita. Sua marca merece o melhor.',
        accentColor: '#00bfff',
        gradient: 'linear-gradient(135deg, #001428 0%, #003366 50%, #0066cc 100%)',
    },
    webapp: {
        id: 'webapp',
        title: 'App Web',
        subtitle: 'Sob Medida',
        description: 'Aplicações web robustas, rápidas e bonitas. Do conceito à produção.',
        accentColor: '#00e676',
        gradient: 'linear-gradient(135deg, #001a00 0%, #003300 50%, #006600 100%)',
    },
};

// ── Templates ──

export const TEMPLATES: TemplateItem[] = [
    // ═══════════ LINK NA BIO (5) ═══════════
    {
        id: 'bio-creator',
        title: 'Social Media Pro',
        description: 'Template ideal para Social Medias, Assessores e Gestores de Tráfego. Destaque seus cases e pacotes.',
        category: 'linknabio',
        gradient: 'linear-gradient(135deg, #1a002e, #4a00a0)',
        accentColor: '#a855f7',
        tags: ['Social Media', 'Marketing', 'Portfólio'],
        badge: 'Popular',
        imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
        logoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
        mockupElements: ['avatar', 'name', 'links-4', 'social-icons'],
    },
    {
        id: 'bio-business',
        title: 'Barba & Navalha',
        description: 'Feito para Barbearias e Salões de Beleza. Agende horários, mostre serviços e rotas.',
        category: 'linknabio',
        gradient: 'linear-gradient(135deg, #0a0a1a, #1a1a3a)',
        accentColor: '#6366f1',
        tags: ['Barbearia', 'Agendamento', 'Salão'],
        imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
        logoUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?w=150&q=80', // Barber shop logo
        mockupElements: ['avatar', 'title', 'links-3', 'contact'],
    },
    {
        id: 'bio-music',
        title: 'Personal Link',
        description: 'Um link na bio focado em pessoas comuns, freelancers ou influenciadores do dia a dia.',
        category: 'linknabio',
        gradient: 'linear-gradient(135deg, #1a0028, #3d005c, #7b00b8)',
        accentColor: '#ec4899',
        tags: ['Pessoal', 'Freelance', 'Contato'],
        badge: 'Novo',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80', // Music microphone studio vibe
        logoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80',
        mockupElements: ['cover-art', 'player', 'links-3', 'tour-dates'],
    },
    {
        id: 'bio-food',
        title: 'Doce Confeitaria',
        description: 'Ideal para confeitarias e deliveries locais. Botões de ação diretos pro iFood ou WhatsApp.',
        category: 'linknabio',
        gradient: 'linear-gradient(135deg, #1a0800, #3d1400, #7a2800)',
        accentColor: '#ff8c42',
        tags: ['Doces', 'Delivery', 'Ifood'],
        imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
        logoUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=150&q=80',
        mockupElements: ['banner', 'menu-grid', 'links-2', 'delivery-btn'],
    },
    {
        id: 'bio-portfolio',
        title: 'Consultor Expert',
        description: 'Design sério e confiável para Advogados, Arquitetos ou Consultores. Foque na conversão.',
        category: 'linknabio',
        gradient: 'linear-gradient(135deg, #0a0a0a, #1a1a1a, #2a2a2a)',
        accentColor: '#1e293b',
        tags: ['Advogado', 'Consultor', 'Reuniões'],
        imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80', // Professional consultant photo
        logoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&q=80',
        mockupElements: ['gallery-grid', 'name', 'links-2', 'cta'],
    },

    // ═══════════ E-COMMERCE (5) ═══════════
    {
        id: 'shop-fashion',
        title: 'Fashion Store',
        description: 'Loja de moda premium com checkout rápido. Sua marca vestida de sucesso.',
        category: 'ecommerce',
        gradient: 'linear-gradient(135deg, #0a0a0a, #1a1a2e, #2e1a3d)',
        accentColor: '#f0a0c0',
        tags: ['Moda', 'Checkout', 'Premium'],
        badge: 'Mais Vendido',
        imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80',
        mockupElements: ['hero-banner', 'product-grid', 'cart-icon', 'categories'],
    },
    {
        id: 'shop-tech',
        title: 'Tech Shop',
        description: 'E-commerce de tecnologia com filtros avançados e comparação de produtos.',
        category: 'ecommerce',
        gradient: 'linear-gradient(135deg, #001428, #003366, #0066cc)',
        accentColor: '#00bfff',
        tags: ['Tech', 'Filtros', 'Comparação'],
        imageUrl: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80',
        mockupElements: ['search-bar', 'product-cards', 'filters', 'reviews'],
    },
    {
        id: 'shop-food',
        title: 'Real Delivery',
        description: 'Cardápio digital avançado com simulação de sacola, categorias e design focado em conversão.',
        category: 'ecommerce',
        gradient: 'linear-gradient(135deg, #2c040d, #8a0c20, #ea1d2c)',
        accentColor: '#ea1d2c',
        tags: ['Delivery', 'Cardápio', 'Sacola'],
        badge: 'Novo',
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
        mockupElements: ['menu-nav', 'prod-card', 'cart-floating', 'price-promo'],
    },
    {
        id: 'shop-beauty',
        title: 'Beauty & Cosmetics',
        description: 'Loja de beleza com provador virtual e recomendações personalizadas.',
        category: 'ecommerce',
        gradient: 'linear-gradient(135deg, #1a0020, #3d0048, #6b0080)',
        accentColor: '#d946ef',
        tags: ['Beleza', 'Virtual', 'Personalizado'],
        imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80', // Cosmetic products hero
        logoUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=150&q=80', // Beauty profile
        mockupElements: ['hero-video', 'product-carousel', 'reviews', 'wishlist'],
    },
    {
        id: 'shop-digital',
        title: 'Digital Products',
        description: 'Venda cursos, ebooks e templates com entrega automática e dashboard.',
        category: 'ecommerce',
        gradient: 'linear-gradient(135deg, #001a1a, #003333, #006666)',
        accentColor: '#14b8a6',
        tags: ['Digital', 'Cursos', 'Automação'],
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
        mockupElements: ['product-hero', 'pricing-cards', 'testimonials', 'checkout'],
    },

    // ═══════════ SITES (5) ═══════════
    {
        id: 'site-restaurant',
        title: 'Restaurante Premium',
        description: 'Site para restaurantes de alto padrão com cardápio digital e reservas.',
        category: 'sites',
        gradient: 'linear-gradient(135deg, #1a0800, #3d1400, #5c2000)',
        accentColor: '#ff8c42',
        tags: ['Food', 'Reservas', 'Cardápio'],
        badge: 'Popular',
        imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
        mockupElements: ['hero-fullscreen', 'menu-section', 'reservation-form', 'gallery'],
    },
    {
        id: 'site-corporate',
        title: 'Corporate Tech',
        description: 'Site institucional para empresas de tecnologia. Autoridade e confiança.',
        category: 'sites',
        gradient: 'linear-gradient(135deg, #001428, #002850, #004080)',
        accentColor: '#3b82f6',
        tags: ['Corporate', 'B2B', 'Autoridade'],
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
        mockupElements: ['hero-split', 'stats-bar', 'services-grid', 'contact-form'],
    },
    {
        id: 'site-clinic',
        title: 'Clínica Saúde',
        description: 'Site para clínicas médicas e odontológicas. Agendamento e credibilidade.',
        category: 'sites',
        gradient: 'linear-gradient(135deg, #001a2e, #00334d, #005580)',
        accentColor: '#00d4ff',
        tags: ['Saúde', 'Agendamento', 'Confiança'],
        badge: 'Novo',
        imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80',
        mockupElements: ['hero-doctor', 'services-cards', 'booking-widget', 'map'],
    },
    {
        id: 'site-realstate',
        title: 'Imobiliária Luxo',
        description: 'Site para imobiliárias com tour virtual e busca avançada de imóveis.',
        category: 'sites',
        gradient: 'linear-gradient(135deg, #0a0a1a, #1a1a3a, #2a2a5a)',
        accentColor: '#c9a96e',
        tags: ['Imóveis', 'Tour Virtual', 'Busca'],
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        mockupElements: ['hero-property', 'search-filters', 'property-grid', 'contact'],
    },
    {
        id: 'site-gym',
        title: 'Fitness & Gym',
        description: 'Site para academias com planos, horários e área do aluno integrada.',
        category: 'sites',
        gradient: 'linear-gradient(135deg, #001a00, #003300, #005500)',
        accentColor: '#00e676',
        tags: ['Fitness', 'Planos', 'Aluno'],
        imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
        mockupElements: ['hero-dynamic', 'plans-pricing', 'trainers', 'schedule'],
    },

    // ═══════════ APP WEB (2) ═══════════
    {
        id: 'app-tasks',
        title: 'TaskFlow',
        description: 'Gerenciador de tarefas com CRUD completo, filtros, prioridades e progresso visual.',
        category: 'webapp',
        gradient: 'linear-gradient(135deg, #0a0a14, #14142e, #1e1e48)',
        accentColor: '#6366f1',
        tags: ['Tarefas', 'Produtividade', 'CRUD'],
        badge: 'Novo',
        imageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80',
        mockupElements: ['progress-bar', 'task-list', 'filters', 'add-input'],
    },
    {
        id: 'app-kanban',
        title: 'K-Board',
        description: 'Quadro Kanban estilo Trello. Colunas de tarefas, etiquetas coloridas e multi-usuários.',
        category: 'webapp',
        gradient: 'linear-gradient(135deg, #0052cc, #0747a6, #172b4d)',
        accentColor: '#0052cc',
        tags: ['Kanban', 'Ágil', 'Projetos'],
        badge: 'Novo',
        imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80',
        mockupElements: ['board-columns', 'draggable-cards', 'labels', 'members'],
    },
];
