import { TemplateItem, ShowcasePageData } from './types';

// ── Page Configs ──
export const SHOWCASE_PAGES: Record<string, ShowcasePageData> = {
    linknabio: {
        id: 'linknabio',
        title: 'Link na Bio',
        subtitle: 'Personalizado',
        description: 'Transforme seu perfil em uma vitrine profissional. Seu público vai clicar.',
        accentColor: '#a855f7',
        gradient: 'linear-gradient(135deg, #1a002e 0%, #3d0068 50%, #7b00cc 100%)',
    },
    ecommerce: {
        id: 'ecommerce',
        title: 'E-commerce',
        subtitle: 'Lojas que Vendem',
        description: 'Lojas online que convertem visitantes em compradores. Design que vende.',
        accentColor: '#f59e0b',
        gradient: 'linear-gradient(135deg, #1a0e00 0%, #3d2800 50%, #7a5000 100%)',
    },
    sites: {
        id: 'sites',
        title: 'Sites',
        subtitle: 'Impactantes',
        description: 'Sites que impressionam na primeira visita. Sua marca merece o melhor.',
        accentColor: '#22d3ee',
        gradient: 'linear-gradient(135deg, #001428 0%, #003366 50%, #0066cc 100%)',
    },
    webapp: {
        id: 'webapp',
        title: 'App Web',
        subtitle: 'Sob Medida',
        description: 'Aplicações web robustas, rápidas e bonitas. Do conceito à produção.',
        accentColor: '#34d399',
        gradient: 'linear-gradient(135deg, #001a00 0%, #003300 50%, #006600 100%)',
    },
};

// ── Templates ──
// Cada template usa mockup CSS vivo (sem imagens externas) definido pelo mockupKind.

export const TEMPLATES: TemplateItem[] = [
    // ═══════════ LINK NA BIO (5) ═══════════
    {
        id: 'bio-creator',
        title: 'Social Media Pro',
        description: 'Template ideal para Social Medias, Assessores e Gestores de Tráfego. Destaque seus cases e pacotes.',
        category: 'linknabio',
        accentColor: '#a855f7',
        tags: ['Social Media', 'Marketing', 'Portfólio'],
        badge: 'Popular',
        mockupKind: 'bio',
        mockupLines: ['Meus Serviços', 'Cases & Resultados', 'Agendar Consultoria', 'Instagram'],
    },
    {
        id: 'bio-business',
        title: 'Barba & Navalha',
        description: 'Feito para Barbearias e Salões de Beleza. Agende horários, mostre serviços e rotas.',
        category: 'linknabio',
        accentColor: '#6366f1',
        tags: ['Barbearia', 'Agendamento', 'Salão'],
        mockupKind: 'bio',
        mockupLines: ['Agendar Horário', 'Nossos Serviços', 'Tabela de Preços', 'Como Chegar'],
    },
    {
        id: 'bio-music',
        title: 'Personal Link',
        description: 'Um link na bio focado em pessoas comuns, freelancers ou influenciadores do dia a dia.',
        category: 'linknabio',
        accentColor: '#ec4899',
        tags: ['Pessoal', 'Freelance', 'Contato'],
        badge: 'Novo',
        mockupKind: 'bio',
        mockupLines: ['Meu Portfólio', 'WhatsApp', 'Currículo', 'Redes Sociais'],
    },
    {
        id: 'bio-food',
        title: 'Doce Confeitaria',
        description: 'Ideal para confeitarias e deliveries locais. Botões de ação diretos pro iFood ou WhatsApp.',
        category: 'linknabio',
        accentColor: '#ff8c42',
        tags: ['Doces', 'Delivery', 'Ifood'],
        mockupKind: 'bio',
        mockupLines: ['Pedir no WhatsApp', 'Ver Cardápio', 'Pedir no iFood', 'Endereço'],
    },
    {
        id: 'bio-portfolio',
        title: 'Consultor Expert',
        description: 'Design sério e confiável para Advogados, Arquitetos ou Consultores. Foque na conversão.',
        category: 'linknabio',
        accentColor: '#94a3b8',
        tags: ['Advogado', 'Consultor', 'Reuniões'],
        mockupKind: 'bio',
        mockupLines: ['Agendar Reunião', 'Sobre Mim', 'Meus Serviços', 'LinkedIn'],
    },

    // ═══════════ E-COMMERCE (5) ═══════════
    {
        id: 'shop-fashion',
        title: 'Fashion Store',
        description: 'Loja de moda premium com checkout rápido. Sua marca vestida de sucesso.',
        category: 'ecommerce',
        accentColor: '#f472b6',
        tags: ['Moda', 'Checkout', 'Premium'],
        badge: 'Mais Vendido',
        mockupKind: 'shop',
        mockupLines: ['Vestidos', 'Calçados', 'Acessórios', 'Carrinho'],
        mockupExtra: 'fashion',
    },
    {
        id: 'shop-tech',
        title: 'Tech Shop',
        description: 'E-commerce de tecnologia com filtros avançados e comparação de produtos.',
        category: 'ecommerce',
        accentColor: '#22d3ee',
        tags: ['Tech', 'Filtros', 'Comparação'],
        mockupKind: 'shop',
        mockupLines: ['Smartphones', 'Notebooks', 'Acessórios', 'Promoções'],
    },
    {
        id: 'shop-food',
        title: 'Real Delivery',
        description: 'Cardápio digital avançado com simulação de sacola, categorias e design focado em conversão.',
        category: 'ecommerce',
        accentColor: '#ef4444',
        tags: ['Delivery', 'Cardápio', 'Sacola'],
        badge: 'Novo',
        mockupKind: 'shop',
        mockupLines: ['Lanches', 'Pizzas', 'Bebidas', 'Sacola (2)'],
    },
    {
        id: 'shop-beauty',
        title: 'Beauty & Cosmetics',
        description: 'Loja de beleza com vitrine elegante, avaliações e recomendações personalizadas.',
        category: 'ecommerce',
        accentColor: '#d946ef',
        tags: ['Beleza', 'Vitrine', 'Personalizado'],
        mockupKind: 'shop',
        mockupLines: ['Skincare', 'Maquiagem', 'Perfumes', 'Mais Amados'],
    },
    {
        id: 'shop-digital',
        title: 'Digital Products',
        description: 'Venda cursos, ebooks e templates com entrega automática e dashboard.',
        category: 'ecommerce',
        accentColor: '#14b8a6',
        tags: ['Digital', 'Cursos', 'Automação'],
        mockupKind: 'shop',
        mockupLines: ['Cursos', 'E-books', 'Templates', 'Área do Aluno'],
    },

    // ═══════════ SITES (5) ═══════════
    {
        id: 'site-restaurant',
        title: 'Restaurante Premium',
        description: 'Site para restaurantes de alto padrão com cardápio digital e reservas.',
        category: 'sites',
        accentColor: '#fb923c',
        tags: ['Food', 'Reservas', 'Cardápio'],
        badge: 'Popular',
        mockupKind: 'site',
        mockupLines: ['Cardápio', 'Reservas', 'Nossa História'],
    },
    {
        id: 'site-corporate',
        title: 'Corporate Tech',
        description: 'Site institucional para empresas de tecnologia. Autoridade e confiança.',
        category: 'sites',
        accentColor: '#3b82f6',
        tags: ['Corporate', 'B2B', 'Autoridade'],
        mockupKind: 'site',
        mockupLines: ['Soluções', 'Cases', 'Contato'],
    },
    {
        id: 'site-clinic',
        title: 'Clínica Saúde',
        description: 'Site para clínicas médicas e odontológicas. Agendamento e credibilidade.',
        category: 'sites',
        accentColor: '#22d3ee',
        tags: ['Saúde', 'Agendamento', 'Confiança'],
        badge: 'Novo',
        mockupKind: 'site',
        mockupLines: ['Agendar Consulta', 'Especialidades', 'Corpo Clínico'],
    },
    {
        id: 'site-realstate',
        title: 'Imobiliária Luxo',
        description: 'Site para imobiliárias com busca avançada de imóveis e filtros inteligentes.',
        category: 'sites',
        accentColor: '#d4af37',
        tags: ['Imóveis', 'Busca', 'Premium'],
        mockupKind: 'site',
        mockupLines: ['Buscar Imóvel', 'Destaques', 'Fale Conosco'],
    },
    {
        id: 'site-gym',
        title: 'Fitness & Gym',
        description: 'Site para academias com planos, horários e área do aluno integrada.',
        category: 'sites',
        accentColor: '#34d399',
        tags: ['Fitness', 'Planos', 'Aluno'],
        mockupKind: 'site',
        mockupLines: ['Planos', 'Horários', 'Matricule-se'],
    },

    // ═══════════ APP WEB (2) ═══════════
    {
        id: 'app-tasks',
        title: 'TaskFlow',
        description: 'Gerenciador de tarefas com CRUD completo, filtros, prioridades e progresso visual.',
        category: 'webapp',
        accentColor: '#6366f1',
        tags: ['Tarefas', 'Produtividade', 'CRUD'],
        badge: 'Novo',
        mockupKind: 'app',
        mockupLines: ['Minhas Tarefas', 'Em andamento', 'Concluídas'],
    },
    {
        id: 'app-kanban',
        title: 'K-Board',
        description: 'Quadro Kanban estilo Trello. Colunas de tarefas, etiquetas coloridas e multi-usuários.',
        category: 'webapp',
        accentColor: '#0052cc',
        tags: ['Kanban', 'Ágil', 'Projetos'],
        badge: 'Novo',
        mockupKind: 'app',
        mockupLines: ['Backlog', 'Em progresso', 'Feito'],
    },
];
